name: present_now
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0-170.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter  
  flutter_secure_storage: ^9.1.1 #version actualizada
  http: ^1.2.1 #version actualizada   
  geolocator: ^11.0.0 # Versión actualizada del paquete
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^17.1.2 # Actualizada a la última versión
  path_provider: ^2.1.3
  provider: ^6.0.5
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

