name: present_now
description: "A new Flutter project."
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.3.0-170.0.dev <4.0.0'

dependencies:
  animate_do: ^3.3.4
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.1.2
  flutter_map: ^6.1.0
  flutter_secure_storage: ^9.1.1
  geolocator: ^11.0.0
  http: ^1.2.1
  intl: ^0.19.0
  latlong2: ^0.9.1
  open_file: ^3.3.2
  path_provider: ^2.1.3
  pdf: ^3.10.8
  provider: ^6.0.5
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
